---
- name: Install Docker and run container on CentOS machines
  hosts: myservers
  become: true  # Use sudo to install packages
  tasks:
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: marriy/first_repo  # Replace with the actual image name
        tag: latest  # You can specify another tag if needed

    - name: Run Docker container
      docker_container:
        name: your_container_name  # Replace with your desired container name
        image: marriy/first_repo:latest  # Use the same image name as above
        state: started
