---
- name: Install Docker on CentOS VMs
  hosts: myservers
  become: yes  # Use sudo
  tasks:
    - name: Ensure the latest version of Docker is installed
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
