---
- name: Install Docker on CentOS VMs
  hosts: myservers
  become: yes  # Use sudo
  tasks:
    - name: Remove podman-docker if installed
      yum:
        name: podman-docker
        state: absent
      ignore_errors: yes

    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Set up the Docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Add user to docker group
      command: usermod -aG docker {{ ansible_user }}
      ignore_errors: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Restart Docker service
      service:
        name: docker
        state: restarted

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: marriy/first_repo
        tag: latest
        source: pull

    - name: Run Docker container from image
      docker_container:
        name: first_repo_container
        image: "marriy/first_repo:latest"
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"
