---
- name: Install Docker on CentOS VMs
  hosts: myservers
  become: yes  # Use sudo
  tasks:
    - name: Remove podman-docker if installed
      yum:
        name: podman-docker
        state: absent
      ignore_errors: yes  # Continue if podman-docker is not found

    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Set up the Docker repository
      command: >
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check Docker version
      command: docker --version
      register: docker_version

    - name: Display Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Check Docker service status
      systemd:
        name: docker
        state: started
      register: docker_status

    - name: Display Docker service status
      debug:
        msg: "Docker service status: {{ docker_status.status }}"

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: marriy/first_repo
        tag: "{{ lookup('env', 'BUILD_NUMBER') }}"  # Pull using the environment variable
        source: pull  # Specify the source

    - name: Run Docker container from image
      docker_container:
        name: first_repo_container  # Replace with a desired container name
        image: "marriy/first_repo:{{ lookup('env', 'BUILD_NUMBER') }}"
        state: started
        restart_policy: always  # Optional: Set the restart policy
